# Generated by Django 3.1.7 on 2021-03-19 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='emial',
            new_name='email',
        ),
    ]
